#!/bin/bash

# This script runs all checks across the entire project.
scriptDir="$(dirname "$0")"
set -o pipefail
set -eu

"$scriptDir/gradlew" -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home spotlessApply check $@
"$scriptDir/.build/code-convention-checks/check-custom-style"
